services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'music-service'
    container_name: music-service-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5433/music
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2242

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=2242
      - POSTGRES_DB=music
      - PGPORT=5433